# Site settings
title: SwagiRecordz
email: info@swagiRecordz.com
description: > # this means to ignore newlines until "baseurl:"
  Developer Blog of the Haufe Group. 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: SwagiRecordz
github_username:  SwagiRecordz

#Logo of SIte
logo : logo.png

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"

gems:
   - jekyll-youtube
   - jekyll-paginate

collections:
  album:
    output: true
  faq:
    output: true
  privacyTerms:
    output: true